"""Humanoid Locomotion Runtime research scaffold."""

from humanoid_locomotion_runtime.controller_contracts import (
    COMPANY_G1_23DOF_CONTROLLER_CONTRACT,
    COMPANY_G1_23DOF_JOINT_ORDER,
    MJLAB_G1_29DOF_REFERENCE_CONTRACT,
    ControllerProfileContract,
    ObservationTermContract,
    get_controller_contract,
    joint_order_sha256,
)
from humanoid_locomotion_runtime.edp import (
    EDPValidationResult,
    EpisodeDataPackageWriter,
    RuntimeEventLogger,
    assert_valid_episode_data_package,
    validate_episode_data_package,
    write_sample_episode_data_package,
)
from humanoid_locomotion_runtime.schemas import (
    BodyMemoryState,
    EpisodeManifest,
    EpisodeMetrics,
    EpisodeReplayIndex,
    FailureEvent,
    LocomotionCommand,
    LocomotionStatus,
    MemoryTarget,
    OracleAnnotation,
    PolicyObservation,
    RecoveryActionRecord,
    ReplayArtifactRecord,
    RuntimeEvent,
    assert_no_privileged_keys,
    serialize_policy_observation,
)

__version__ = "0.1.0"

__all__ = [
    "BodyMemoryState",
    "COMPANY_G1_23DOF_CONTROLLER_CONTRACT",
    "COMPANY_G1_23DOF_JOINT_ORDER",
    "ControllerProfileContract",
    "EDPValidationResult",
    "EpisodeDataPackageWriter",
    "EpisodeManifest",
    "EpisodeMetrics",
    "EpisodeReplayIndex",
    "FailureEvent",
    "LocomotionCommand",
    "LocomotionStatus",
    "MJLAB_G1_29DOF_REFERENCE_CONTRACT",
    "MemoryTarget",
    "ObservationTermContract",
    "OracleAnnotation",
    "PolicyObservation",
    "RecoveryActionRecord",
    "ReplayArtifactRecord",
    "RuntimeEvent",
    "RuntimeEventLogger",
    "__version__",
    "assert_no_privileged_keys",
    "assert_valid_episode_data_package",
    "get_controller_contract",
    "joint_order_sha256",
    "serialize_policy_observation",
    "validate_episode_data_package",
    "write_sample_episode_data_package",
]
