"""Humanoid Locomotion Runtime research scaffold."""

from humanoid_locomotion_runtime.analysis import (
    DecisionFlipRecord,
    decision_flip_rate,
    extract_decision_flips,
    format_run_id,
)
from humanoid_locomotion_runtime.controller_contracts import (
    COMPANY_G1_23DOF_CONTROLLER_CONTRACT,
    COMPANY_G1_23DOF_JOINT_ORDER,
    MJLAB_G1_29DOF_REFERENCE_CONTRACT,
    ControllerProfileContract,
    ObservationTermContract,
    get_controller_contract,
    joint_order_sha256,
)
from humanoid_locomotion_runtime.dashboard import (
    ALLOWED_DASHBOARD_COMMAND_MODES,
    DashboardFrame,
    DashboardSummary,
    ViserDashboardPublisher,
)
from humanoid_locomotion_runtime.edp import (
    EDPValidationResult,
    EpisodeDataPackageWriter,
    RuntimeEventLogger,
    assert_valid_episode_data_package,
    validate_episode_data_package,
    write_sample_episode_data_package,
)
from humanoid_locomotion_runtime.grounding_memory import (
    ControlledGroundingAdapter,
    ControlledGroundingRecord,
    GroundingSelection,
    TemporaryObjectMemory,
)
from humanoid_locomotion_runtime.navigator import (
    LocalObstacle,
    LocalRoute,
    NavigatorV0,
)
from humanoid_locomotion_runtime.recovery_options import (
    RECOVERY_ACTIONS,
    RECOVERY_OPTION_CONTRACTS,
    RecoveryOptionContract,
    validate_recovery_option_catalog,
)
from humanoid_locomotion_runtime.runtime_manager import (
    FakeRuntimeBackend,
    RuntimeCommandEnvelope,
    RuntimeManager,
    SafetyDecision,
    SafetySupervisor,
)
from humanoid_locomotion_runtime.schemas import (
    BodyMemoryState,
    EpisodeManifest,
    EpisodeMetrics,
    EpisodeReplayIndex,
    FailureEvent,
    LocomotionCommand,
    LocomotionStatus,
    MemoryTarget,
    OracleAnnotation,
    PolicyObservation,
    RecoveryActionRecord,
    ReplayArtifactRecord,
    RuntimeEvent,
    assert_no_privileged_keys,
    serialize_policy_observation,
)
from humanoid_locomotion_runtime.seed_splits import (
    DEFAULT_POLICY_TRAINING_SEEDS,
    DEFAULT_ROOT_SEED,
    DEFAULT_SCENARIO_SPLIT_COUNTS,
    DEFAULT_STRIDE,
    generate_seed_split_toml,
    generate_stride_seed_splits,
)
from humanoid_locomotion_runtime.self_improvement import (
    CandidateUpdateManifest,
    PromotionReport,
    RollbackManifest,
    StrategyMemoryRecord,
    assert_no_forbidden_update_fields,
    find_forbidden_update_key_paths,
)
from humanoid_locomotion_runtime.snapshot_branching import (
    CommonRandomStream,
    DecisionEpoch,
    FakeDeterministicSnapshotProvider,
    SnapshotBranchMetadata,
    SnapshotManifest,
    runtime_payload_sha256,
    validate_sha256_digest,
)

__version__ = "0.1.0"

__all__ = [
    "ALLOWED_DASHBOARD_COMMAND_MODES",
    "BodyMemoryState",
    "COMPANY_G1_23DOF_CONTROLLER_CONTRACT",
    "COMPANY_G1_23DOF_JOINT_ORDER",
    "CandidateUpdateManifest",
    "ControlledGroundingAdapter",
    "ControlledGroundingRecord",
    "ControllerProfileContract",
    "DashboardFrame",
    "DashboardSummary",
    "DecisionFlipRecord",
    "EDPValidationResult",
    "EpisodeDataPackageWriter",
    "EpisodeManifest",
    "EpisodeMetrics",
    "EpisodeReplayIndex",
    "FailureEvent",
    "FakeDeterministicSnapshotProvider",
    "FakeRuntimeBackend",
    "GroundingSelection",
    "LocalObstacle",
    "LocalRoute",
    "LocomotionCommand",
    "LocomotionStatus",
    "MJLAB_G1_29DOF_REFERENCE_CONTRACT",
    "MemoryTarget",
    "NavigatorV0",
    "ObservationTermContract",
    "OracleAnnotation",
    "PolicyObservation",
    "PromotionReport",
    "RECOVERY_ACTIONS",
    "RECOVERY_OPTION_CONTRACTS",
    "RuntimeCommandEnvelope",
    "RuntimeManager",
    "RecoveryActionRecord",
    "RecoveryOptionContract",
    "ReplayArtifactRecord",
    "RollbackManifest",
    "RuntimeEvent",
    "RuntimeEventLogger",
    "SafetyDecision",
    "SafetySupervisor",
    "CommonRandomStream",
    "DecisionEpoch",
    "SnapshotBranchMetadata",
    "SnapshotManifest",
    "StrategyMemoryRecord",
    "TemporaryObjectMemory",
    "ViserDashboardPublisher",
    "__version__",
    "assert_no_forbidden_update_fields",
    "assert_no_privileged_keys",
    "assert_valid_episode_data_package",
    "DEFAULT_POLICY_TRAINING_SEEDS",
    "DEFAULT_ROOT_SEED",
    "DEFAULT_SCENARIO_SPLIT_COUNTS",
    "DEFAULT_STRIDE",
    "decision_flip_rate",
    "extract_decision_flips",
    "find_forbidden_update_key_paths",
    "format_run_id",
    "generate_seed_split_toml",
    "generate_stride_seed_splits",
    "get_controller_contract",
    "joint_order_sha256",
    "runtime_payload_sha256",
    "serialize_policy_observation",
    "validate_recovery_option_catalog",
    "validate_sha256_digest",
    "validate_episode_data_package",
    "write_sample_episode_data_package",
]
